db:
 name: "Cassandra DB Dev123 555555555"
 password: '{cipher}AQAowqKWZqo3nf07jWUU/hZTSH2EXJIwWDqC9WkRU2dorZbgKyi2bflM/vcR6EcC4x9ZTfDfr8UrtRllTnPBeKoJwhh71sYz4ecG7BAAgk0nYKE0/M6sup5SDZRU1gek+cd9V9eRaRyhXGjxUfrvbKEWjU1+F+x/haLlcfhQq8LPyxPN5k9fl6o6yrxt7Mx20diFJxqgT/TyiijviubLOdxRIfXQoj7gbVXVltEdaa3CNqdLtiPxxhIqakm+N27G3xR3PStKwUs1rTjlJBqqLFIk4zaNadVyVdJk8OY65iv+qc7W5QVBcPs9RzZJ4SY00b5Z0otQR8fDUe7JMYkvaciskt6BAvy/XpHlIkHoT6pF2LtpSeW3poib8XO8rBvcwbHXPtyKisW1I9AMZiMUKYin'
